### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by harrisonlingren** [max-barry/google-drive-cms#10]
Hi there Max - would you be able to add a license to this software so it can be used elsewhere? Thanks.

**Comment by harrisonlingren** [comment]
https://choosealicense.com/

**Comment by Remzi1993** [comment]
@harrisonlingren I did a PR
I hope @max-barry will merged the PR, so that other developers are able to use this.

**Comment by Remzi1993** [comment]
Hi @harrisonlingren

A license is added.
@max-barry you could close this issue.

**Comment by harrisonlingren** [comment]
Nice, thanks! (PR #15 for reference)
