### ISSUE TITLE
Nesting documents results in error msg

### ISSUE THREAD

**Issue by dam0** [max-barry/google-drive-cms#11]
When nesting documents references (using IDs), I receive an error message indicating the document cannot be found - 

Document is missing (perhaps it was deleted?)

Can anyone else confirm this behaviour?

-Damo

**Comment by dam0** [comment]
So when trying to open a nested sheet from a nested sheet, it's failing at:

[17-08-03 20:30:20:070 PDT] SpreadsheetApp.open([GAS: 01 - Key messages.docx]) [0.028 seconds]
[17-08-03 20:30:20:172 PDT] Execution failed: Document 1X67A3huhd2RP8jw2IDEvDJ4q-AyjJ8pBIA9qHR5-QpI is missing (perhaps it was deleted?) (line 22, file "BuildJSON") [1.583 seconds total runtime]

**Comment by dam0** [comment]
Working, when using Spreadsheet ID only..

**Comment by bseaver** [comment]
Damo, if you are still struggling with this, try boiling the problem down to the minimum needed to test, then share with me with full edit capability.  Contact me with your e-mail here: http://www.seaver99.com/demo/php/contactform.php and I'll give you my e-mail for sharing purposes.

**Comment by dam0** [comment]
Thanks for the follow up, have got it working using the full URI..
