### ISSUE TITLE
List issue

### ISSUE THREAD

**Issue by JosefJezek** [max-barry/google-drive-cms#2]
Cell contain `aaaa, bbbb`

JSON contain spaces... Please trim string.

```
"aaaa"," bbbb"
```

**Comment by max-barry** [comment]
Hi @JosefJezek 

I want it to be un-opinionated on what data you're sending through.
You format your data using all the power of Google Sheets' built in functions, the Google Drive CMS just packages and sends it to your endpoint.

I don't know (and don't want the system to care) if the user wants to push strings with spaces at the start.

In your example I'd use Sheets' built in TRIM function (https://support.google.com/docs/answer/3094140?hl=en). You can write a Sheets / Excel formula that trims and returns comma delimited items.

**Comment by DaxChen** [comment]
If you want to trim all list items:
1. Click on **Tools > Script Editor**
2. Choose **BuildJSON.gs** file
3. add a `map` function with `trim` on _line **58**_ (or the `function extractList_`) 

```diff
function extractList_(value, settings) {
-  return value.split(settings.listDelimiter);
+  return value.split(settings.listDelimiter).map(function (x) { return x.trim() });
}
```

4. Save and close
5. Rerun script and check output!
